# Generated by Django 3.2.11 on 2022-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
